/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AuthResult = { 'ok' : UserView } |
  { 'deactivated' : null } |
  { 'notFound' : null };
export interface CreateReservationRequest {
  'date' : DateString,
  'guestCount' : bigint,
  'name' : string,
  'notes' : string,
  'phone' : string,
  'leaveTime' : [] | [MinutesFromMidnight],
  'arriveTime' : MinutesFromMidnight,
}
export interface CreateUserRequest { 'name' : string, 'email' : string }
export type DateString = string;
export interface DayHours {
  'day' : DayOfWeek,
  'closeTime' : MinutesFromMidnight,
  'isOpen' : boolean,
  'openTime' : MinutesFromMidnight,
}
export type DayOfWeek = { 'fri' : null } |
  { 'mon' : null } |
  { 'sat' : null } |
  { 'sun' : null } |
  { 'thu' : null } |
  { 'tue' : null } |
  { 'wed' : null };
export type InviteStatus = { 'pending' : null } |
  { 'accepted' : null };
export type MinutesFromMidnight = bigint;
export interface ReservationView {
  'id' : bigint,
  'userId' : UserId,
  'date' : DateString,
  'guestCount' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notes' : string,
  'phone' : string,
  'leaveTime' : [] | [MinutesFromMidnight],
  'arriveTime' : MinutesFromMidnight,
}
export type Timestamp = bigint;
export interface UpdateReservationRequest {
  'id' : bigint,
  'date' : DateString,
  'guestCount' : bigint,
  'name' : string,
  'notes' : string,
  'phone' : string,
  'leaveTime' : [] | [MinutesFromMidnight],
  'arriveTime' : MinutesFromMidnight,
}
export type UserId = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserView {
  'id' : UserId,
  'inviteStatus' : InviteStatus,
  'inviteToken' : string,
  'principal' : [] | [Principal],
  'name' : string,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'email' : string,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptInvite' : ActorMethod<[string], [] | [UserView]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createReservation' : ActorMethod<
    [CreateReservationRequest],
    ReservationView
  >,
  'createUser' : ActorMethod<[CreateUserRequest], string>,
  'deactivateUser' : ActorMethod<[UserId], boolean>,
  'deleteReservation' : ActorMethod<[bigint], boolean>,
  'getAllOpenHours' : ActorMethod<[], Array<DayHours>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMe' : ActorMethod<[], AuthResult>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listReservationsByDate' : ActorMethod<[DateString], Array<ReservationView>>,
  'listUsers' : ActorMethod<[], Array<UserView>>,
  'setDayHours' : ActorMethod<[DayHours], undefined>,
  'updateReservation' : ActorMethod<[UpdateReservationRequest], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];