/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Nat;
export const InviteStatus = IDL.Variant({
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserView = IDL.Record({
  'id' : UserId,
  'inviteStatus' : InviteStatus,
  'inviteToken' : IDL.Text,
  'principal' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DateString = IDL.Text;
export const MinutesFromMidnight = IDL.Nat;
export const CreateReservationRequest = IDL.Record({
  'date' : DateString,
  'guestCount' : IDL.Nat,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'leaveTime' : IDL.Opt(MinutesFromMidnight),
  'arriveTime' : MinutesFromMidnight,
});
export const ReservationView = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'date' : DateString,
  'guestCount' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'leaveTime' : IDL.Opt(MinutesFromMidnight),
  'arriveTime' : MinutesFromMidnight,
});
export const CreateUserRequest = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const DayOfWeek = IDL.Variant({
  'fri' : IDL.Null,
  'mon' : IDL.Null,
  'sat' : IDL.Null,
  'sun' : IDL.Null,
  'thu' : IDL.Null,
  'tue' : IDL.Null,
  'wed' : IDL.Null,
});
export const DayHours = IDL.Record({
  'day' : DayOfWeek,
  'closeTime' : MinutesFromMidnight,
  'isOpen' : IDL.Bool,
  'openTime' : MinutesFromMidnight,
});
export const AuthResult = IDL.Variant({
  'ok' : UserView,
  'deactivated' : IDL.Null,
  'notFound' : IDL.Null,
});
export const UpdateReservationRequest = IDL.Record({
  'id' : IDL.Nat,
  'date' : DateString,
  'guestCount' : IDL.Nat,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'leaveTime' : IDL.Opt(MinutesFromMidnight),
  'arriveTime' : MinutesFromMidnight,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptInvite' : IDL.Func([IDL.Text], [IDL.Opt(UserView)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createReservation' : IDL.Func(
      [CreateReservationRequest],
      [ReservationView],
      [],
    ),
  'createUser' : IDL.Func([CreateUserRequest], [IDL.Text], []),
  'deactivateUser' : IDL.Func([UserId], [IDL.Bool], []),
  'deleteReservation' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllOpenHours' : IDL.Func([], [IDL.Vec(DayHours)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMe' : IDL.Func([], [AuthResult], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listReservationsByDate' : IDL.Func(
      [DateString],
      [IDL.Vec(ReservationView)],
      ['query'],
    ),
  'listUsers' : IDL.Func([], [IDL.Vec(UserView)], ['query']),
  'setDayHours' : IDL.Func([DayHours], [], []),
  'updateReservation' : IDL.Func([UpdateReservationRequest], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Nat;
  const InviteStatus = IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserView = IDL.Record({
    'id' : UserId,
    'inviteStatus' : InviteStatus,
    'inviteToken' : IDL.Text,
    'principal' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DateString = IDL.Text;
  const MinutesFromMidnight = IDL.Nat;
  const CreateReservationRequest = IDL.Record({
    'date' : DateString,
    'guestCount' : IDL.Nat,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'leaveTime' : IDL.Opt(MinutesFromMidnight),
    'arriveTime' : MinutesFromMidnight,
  });
  const ReservationView = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'date' : DateString,
    'guestCount' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'leaveTime' : IDL.Opt(MinutesFromMidnight),
    'arriveTime' : MinutesFromMidnight,
  });
  const CreateUserRequest = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const DayOfWeek = IDL.Variant({
    'fri' : IDL.Null,
    'mon' : IDL.Null,
    'sat' : IDL.Null,
    'sun' : IDL.Null,
    'thu' : IDL.Null,
    'tue' : IDL.Null,
    'wed' : IDL.Null,
  });
  const DayHours = IDL.Record({
    'day' : DayOfWeek,
    'closeTime' : MinutesFromMidnight,
    'isOpen' : IDL.Bool,
    'openTime' : MinutesFromMidnight,
  });
  const AuthResult = IDL.Variant({
    'ok' : UserView,
    'deactivated' : IDL.Null,
    'notFound' : IDL.Null,
  });
  const UpdateReservationRequest = IDL.Record({
    'id' : IDL.Nat,
    'date' : DateString,
    'guestCount' : IDL.Nat,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'leaveTime' : IDL.Opt(MinutesFromMidnight),
    'arriveTime' : MinutesFromMidnight,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptInvite' : IDL.Func([IDL.Text], [IDL.Opt(UserView)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createReservation' : IDL.Func(
        [CreateReservationRequest],
        [ReservationView],
        [],
      ),
    'createUser' : IDL.Func([CreateUserRequest], [IDL.Text], []),
    'deactivateUser' : IDL.Func([UserId], [IDL.Bool], []),
    'deleteReservation' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllOpenHours' : IDL.Func([], [IDL.Vec(DayHours)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMe' : IDL.Func([], [AuthResult], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listReservationsByDate' : IDL.Func(
        [DateString],
        [IDL.Vec(ReservationView)],
        ['query'],
      ),
    'listUsers' : IDL.Func([], [IDL.Vec(UserView)], ['query']),
    'setDayHours' : IDL.Func([DayHours], [], []),
    'updateReservation' : IDL.Func([UpdateReservationRequest], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };