/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface CreateUserRequest {
    name: string;
    email: string;
}
export interface UserView {
    id: UserId;
    inviteStatus: InviteStatus;
    inviteToken: string;
    principal?: Principal;
    name: string;
    createdAt: Timestamp;
    isActive: boolean;
    email: string;
}
export interface CreateReservationRequest {
    date: DateString;
    guestCount: bigint;
    name: string;
    notes: string;
    phone: string;
    leaveTime?: MinutesFromMidnight;
    arriveTime: MinutesFromMidnight;
}
export interface UpdateReservationRequest {
    id: bigint;
    date: DateString;
    guestCount: bigint;
    name: string;
    notes: string;
    phone: string;
    leaveTime?: MinutesFromMidnight;
    arriveTime: MinutesFromMidnight;
}
export type UserId = bigint;
export interface DayHours {
    day: DayOfWeek;
    closeTime: MinutesFromMidnight;
    isOpen: boolean;
    openTime: MinutesFromMidnight;
}
export type MinutesFromMidnight = bigint;
export interface ReservationView {
    id: bigint;
    userId: UserId;
    date: DateString;
    guestCount: bigint;
    name: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    notes: string;
    phone: string;
    leaveTime?: MinutesFromMidnight;
    arriveTime: MinutesFromMidnight;
}
export type DateString = string;
export type AuthResult = {
    __kind__: "ok";
    ok: UserView;
} | {
    __kind__: "deactivated";
    deactivated: null;
} | {
    __kind__: "notFound";
    notFound: null;
};
export enum DayOfWeek {
    fri = "fri",
    mon = "mon",
    sat = "sat",
    sun = "sun",
    thu = "thu",
    tue = "tue",
    wed = "wed"
}
export enum InviteStatus {
    pending = "pending",
    accepted = "accepted"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    acceptInvite(inviteToken: string): Promise<UserView | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createReservation(req: CreateReservationRequest): Promise<ReservationView>;
    createUser(req: CreateUserRequest): Promise<string>;
    deactivateUser(userId: UserId): Promise<boolean>;
    deleteReservation(id: bigint): Promise<boolean>;
    getAllOpenHours(): Promise<Array<DayHours>>;
    getCallerUserRole(): Promise<UserRole>;
    getMe(): Promise<AuthResult>;
    isCallerAdmin(): Promise<boolean>;
    listReservationsByDate(date: DateString): Promise<Array<ReservationView>>;
    listUsers(): Promise<Array<UserView>>;
    setDayHours(dayHours: DayHours): Promise<void>;
    updateReservation(req: UpdateReservationRequest): Promise<boolean>;
}
import type { AuthResult as _AuthResult, CreateReservationRequest as _CreateReservationRequest, DateString as _DateString, DayHours as _DayHours, DayOfWeek as _DayOfWeek, InviteStatus as _InviteStatus, MinutesFromMidnight as _MinutesFromMidnight, ReservationView as _ReservationView, Timestamp as _Timestamp, UpdateReservationRequest as _UpdateReservationRequest, UserId as _UserId, UserRole as _UserRole, UserView as _UserView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async acceptInvite(arg0: string): Promise<UserView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptInvite(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptInvite(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createReservation(arg0: CreateReservationRequest): Promise<ReservationView> {
        if (this.processError) {
            try {
                const result = await this.actor.createReservation(to_candid_CreateReservationRequest_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ReservationView_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReservation(to_candid_CreateReservationRequest_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ReservationView_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUser(arg0: CreateUserRequest): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0);
            return result;
        }
    }
    async deactivateUser(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateUser(arg0);
            return result;
        }
    }
    async deleteReservation(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReservation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReservation(arg0);
            return result;
        }
    }
    async getAllOpenHours(): Promise<Array<DayHours>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOpenHours();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOpenHours();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMe(): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getMe();
                return from_candid_AuthResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMe();
            return from_candid_AuthResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listReservationsByDate(arg0: DateString): Promise<Array<ReservationView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReservationsByDate(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReservationsByDate(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<UserView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async setDayHours(arg0: DayHours): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDayHours(to_candid_DayHours_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDayHours(to_candid_DayHours_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateReservation(arg0: UpdateReservationRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReservation(to_candid_UpdateReservationRequest_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReservation(to_candid_UpdateReservationRequest_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AuthResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult): AuthResult {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_DayHours_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DayHours): DayHours {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_DayOfWeek_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DayOfWeek): DayOfWeek {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_InviteStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InviteStatus): InviteStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ReservationView_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReservationView): ReservationView {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserView_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserView): UserView {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserView]): UserView | null {
    return value.length === 0 ? null : from_candid_UserView_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MinutesFromMidnight]): MinutesFromMidnight | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: _UserId;
    date: _DateString;
    guestCount: bigint;
    name: string;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    notes: string;
    phone: string;
    leaveTime: [] | [_MinutesFromMidnight];
    arriveTime: _MinutesFromMidnight;
}): {
    id: bigint;
    userId: UserId;
    date: DateString;
    guestCount: bigint;
    name: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    notes: string;
    phone: string;
    leaveTime?: MinutesFromMidnight;
    arriveTime: MinutesFromMidnight;
} {
    return {
        id: value.id,
        userId: value.userId,
        date: value.date,
        guestCount: value.guestCount,
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        notes: value.notes,
        phone: value.phone,
        leaveTime: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.leaveTime)),
        arriveTime: value.arriveTime
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: _DayOfWeek;
    closeTime: _MinutesFromMidnight;
    isOpen: boolean;
    openTime: _MinutesFromMidnight;
}): {
    day: DayOfWeek;
    closeTime: MinutesFromMidnight;
    isOpen: boolean;
    openTime: MinutesFromMidnight;
} {
    return {
        day: from_candid_DayOfWeek_n17(_uploadFile, _downloadFile, value.day),
        closeTime: value.closeTime,
        isOpen: value.isOpen,
        openTime: value.openTime
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    inviteStatus: _InviteStatus;
    inviteToken: string;
    principal: [] | [Principal];
    name: string;
    createdAt: _Timestamp;
    isActive: boolean;
    email: string;
}): {
    id: UserId;
    inviteStatus: InviteStatus;
    inviteToken: string;
    principal?: Principal;
    name: string;
    createdAt: Timestamp;
    isActive: boolean;
    email: string;
} {
    return {
        id: value.id,
        inviteStatus: from_candid_InviteStatus_n4(_uploadFile, _downloadFile, value.inviteStatus),
        inviteToken: value.inviteToken,
        principal: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.principal)),
        name: value.name,
        createdAt: value.createdAt,
        isActive: value.isActive,
        email: value.email
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fri: null;
} | {
    mon: null;
} | {
    sat: null;
} | {
    sun: null;
} | {
    thu: null;
} | {
    tue: null;
} | {
    wed: null;
}): DayOfWeek {
    return "fri" in value ? DayOfWeek.fri : "mon" in value ? DayOfWeek.mon : "sat" in value ? DayOfWeek.sat : "sun" in value ? DayOfWeek.sun : "thu" in value ? DayOfWeek.thu : "tue" in value ? DayOfWeek.tue : "wed" in value ? DayOfWeek.wed : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserView;
} | {
    deactivated: null;
} | {
    notFound: null;
}): {
    __kind__: "ok";
    ok: UserView;
} | {
    __kind__: "deactivated";
    deactivated: null;
} | {
    __kind__: "notFound";
    notFound: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserView_n2(_uploadFile, _downloadFile, value.ok)
    } : "deactivated" in value ? {
        __kind__: "deactivated",
        deactivated: value.deactivated
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    accepted: null;
}): InviteStatus {
    return "pending" in value ? InviteStatus.pending : "accepted" in value ? InviteStatus.accepted : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DayHours>): Array<DayHours> {
    return value.map((x)=>from_candid_DayHours_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReservationView>): Array<ReservationView> {
    return value.map((x)=>from_candid_ReservationView_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserView>): Array<UserView> {
    return value.map((x)=>from_candid_UserView_n2(_uploadFile, _downloadFile, x));
}
function to_candid_CreateReservationRequest_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateReservationRequest): _CreateReservationRequest {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_DayHours_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayHours): _DayHours {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_DayOfWeek_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): _DayOfWeek {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateReservationRequest_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateReservationRequest): _UpdateReservationRequest {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: DateString;
    guestCount: bigint;
    name: string;
    notes: string;
    phone: string;
    leaveTime?: MinutesFromMidnight;
    arriveTime: MinutesFromMidnight;
}): {
    date: _DateString;
    guestCount: bigint;
    name: string;
    notes: string;
    phone: string;
    leaveTime: [] | [_MinutesFromMidnight];
    arriveTime: _MinutesFromMidnight;
} {
    return {
        date: value.date,
        guestCount: value.guestCount,
        name: value.name,
        notes: value.notes,
        phone: value.phone,
        leaveTime: value.leaveTime ? candid_some(value.leaveTime) : candid_none(),
        arriveTime: value.arriveTime
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: DayOfWeek;
    closeTime: MinutesFromMidnight;
    isOpen: boolean;
    openTime: MinutesFromMidnight;
}): {
    day: _DayOfWeek;
    closeTime: _MinutesFromMidnight;
    isOpen: boolean;
    openTime: _MinutesFromMidnight;
} {
    return {
        day: to_candid_DayOfWeek_n27(_uploadFile, _downloadFile, value.day),
        closeTime: value.closeTime,
        isOpen: value.isOpen,
        openTime: value.openTime
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: DateString;
    guestCount: bigint;
    name: string;
    notes: string;
    phone: string;
    leaveTime?: MinutesFromMidnight;
    arriveTime: MinutesFromMidnight;
}): {
    id: bigint;
    date: _DateString;
    guestCount: bigint;
    name: string;
    notes: string;
    phone: string;
    leaveTime: [] | [_MinutesFromMidnight];
    arriveTime: _MinutesFromMidnight;
} {
    return {
        id: value.id,
        date: value.date,
        guestCount: value.guestCount,
        name: value.name,
        notes: value.notes,
        phone: value.phone,
        leaveTime: value.leaveTime ? candid_some(value.leaveTime) : candid_none(),
        arriveTime: value.arriveTime
    };
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): {
    fri: null;
} | {
    mon: null;
} | {
    sat: null;
} | {
    sun: null;
} | {
    thu: null;
} | {
    tue: null;
} | {
    wed: null;
} {
    return value == DayOfWeek.fri ? {
        fri: null
    } : value == DayOfWeek.mon ? {
        mon: null
    } : value == DayOfWeek.sat ? {
        sat: null
    } : value == DayOfWeek.sun ? {
        sun: null
    } : value == DayOfWeek.thu ? {
        thu: null
    } : value == DayOfWeek.tue ? {
        tue: null
    } : value == DayOfWeek.wed ? {
        wed: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
